title: "Fabius Gr端nhangen"
author:
  name: "Fabius Gr端nhagen"
description: >- # this means to ignore newlines until "url:"
  "Fabius Gr端nhagen - Software Developer and CS Master Student @ ETH Z端rich"
url: "https://gruefa.me"
github_username: "gruefa"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
